export const APP_INFO = {
  name: "mmingle",
  title: "mmingle",
  titleTemplate: "%s - mmingle",
  description: "Local Based Social Network",
  url: "https://mmingle.com",
  keywords: [
    "mmingle",
    "local",
    "social network",
    "community",
    "location-based",
    "chat",
    "events",
    "meetup",
    "friends",
    "connections",
    "local events",
    "socializing",
    "networking",
    "local community",
    "social app",
    "meet new people",
    "local social network",
    "community app",
    "local connections",
    "social interaction",
  ],
  authors: [
    {
      name: "ZERONINEZ",
      url: "https://zeroninez.com",
    },
  ],
};
